output: main.o OpenHashTable.o  LinkedList.o ChainHashTable.o Node.o
	g++ main.o OpenHashTable.o  LinkedList.o ChainHashTable.o Node.o  -o hw4 -std=c++11

main.o: main.cpp
	g++ -c main.cpp -std=c++11

OpenHashTable.o: OpenHashTable.cpp OpenHashTable.h
	g++ -c OpenHashTable.cpp -std=c++11

LinkedList.o: LinkedList.cpp LinkedList.h
	g++ -c LinkedList.cpp -std=c++11

ChainHashTable.o: ChainHashTable.cpp ChainHashTable.h
	g++ -c ChainHashTable.cpp -std=c++11

Node.o: Node.cpp Node.h
	g++ -c Node.cpp -std=c++11




