output: main.o HuffmanCode.o HuffmanHeap.o HuffmanQueue.o MaxHeap.o MinHeap.o
	g++ main.o HuffmanCode.o HuffmanHeap.o HuffmanQueue.o MaxHeap.o MinHeap.o -o hw3

main.o: main.cpp
	g++ -c main.cpp

HuffmanCode.o: HuffmanCode.cpp HuffmanCode.h
	g++ -c HuffmanCode.cpp

HuffmanHeap.o: HuffmanHeap.cpp HuffmanHeap.h
	g++ -c HuffmanHeap.cpp

HuffmanQueue.o: HuffmanQueue.cpp HuffmanQueue.h
	g++ -c HuffmanQueue.cpp

MaxHeap.o: MaxHeap.cpp MaxHeap.h
	g++ -c MaxHeap.cpp

MinHeap.o: MinHeap.cpp MinHeap.h
	g++ -c MinHeap.cpp



