output: main.o BST.o BSTNode.o
	g++ main.o BST.o BSTNode.o -o hw2

main.o: main.cpp
	g++ -c main.cpp

BST.o: BST.cpp BST.h
	g++ -c BST.cpp

BSTNode.o: BSTNode.cpp BSTNode.h
	g++ -c BSTNode.cpp

